In [3]:
import yfinance as yf
import pandas as pd
import numpy as np
import ta

In [4]:
print("Downloading stock data for ADMR.JK...")
df = yf.download('ADMR.JK', start='2022-01-01')
df.head()

Downloading stock data for ADMR.JK...

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker         ADMR.JK     ADMR.JK     ADMR.JK     ADMR.JK   ADMR.JK
Date
2022-01-03  128.670883  128.670883  128.670883  128.670883  34289600
2022-01-04  173.467422  173.467422  173.467422  173.467422  22170900
2022-01-05  232.560715  232.560715  209.685890  209.685890  43203600
2022-01-06  289.747772  289.747772  289.747772  289.747772  52097500
2022-01-07  362.184723  362.184723  362.184723  362.184723  19248600

In [5]:
#delete multi index
if isinstance(df.columns, pd. MultiIndex):
    df.columns = df.columns.droplevel(1)
df.head()

Price            Close        High         Low        Open    Volume
Date
2022-01-03  128.670883  128.670883  128.670883  128.670883  34289600
2022-01-04  173.467422  173.467422  173.467422  173.467422  22170900
2022-01-05  232.560715  232.560715  209.685890  209.685890  43203600
2022-01-06  289.747772  289.747772  289.747772  289.747772  52097500
2022-01-07  362.184723  362.184723  362.184723  362.184723  19248600